service: aws-node-http-api-typescript
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs20.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
